services:
  app:
    container_name: app
    build: .
    ports:
      - '3001:3001'
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5432:5432'
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=docker
